### ISSUE TITLE
[TBC Beta] SetBackdrop function not found.

### ISSUE THREAD

**Issue by nieejl** [AaronV-T/AutoBiographer#11]
The 'SetBackdrop' function is not available for most frames, and causes the addon to throw errors upon loading it. More info can be found here: [https://www.wowinterface.com/forums/showthread.php?t=58109](https://www.wowinterface.com/forums/showthread.php?t=58109)

**Comment by nieejl** [comment]
I seem to have fixed this issue in a commit (forked repo).
https://github.com/nieejl/AutoBiographer/commit/2b0e718b4477a7533e7dc6d3e2009fe15b47b5f4
This will not work on the live version, as it requires the BackDropTemplate, which is a thing from the Shadowlands client from what I can see.

Other findings from beta: addon seems to work as intended, however I can't access the options. This seems to be be an issue for all addons at the moment.

**Comment by AaronV-T** [comment]
It looks like there's a mixin we can test for before inheriting from the BackdropTemplate that should allow for backwards compatability, but I would like all these changes for TBC to be in their own branch for now. I have a branch for TBC which I'm working on right now, but I haven't pushed it yet. Tonight I will try to get that branch pushed with this backdrop fix for you to test.

**Comment by nieejl** [comment]
If it's the code posted by Fizzlemizz (link below) it does seem to work on the beta as well as live.
https://www.wowinterface.com/forums/showpost.php?p=336419&postcount=8

**Comment by AaronV-T** [comment]
I took a minute to push the `tbc` branch with nothing more than a simple version change. If you would like, you can make a pull request to that branch with the fix. If not, I will commit the fix to it later tonight.
