### ISSUE TITLE
"Time played this class (Wrath of the Lich King): x days x hours x minutes" spam 

### ISSUE THREAD

**Issue by Pocokk** [AaronV-T/AutoBiographer#22]
Title.

This (system) message (yellow colored) is written in the chat on every minute, which is quite irritating. 

[https://i.imgur.com/7mF6PK2.png](url)

**Comment by AaronV-T** [comment]
Interesting. I have never seen that message. The normal `/played` message says:

> Total time played:
> Time played this level: 

Do you have another addon that is modifying the message? Does it still print the message if you disable all other addons except AutoBiographer?

**Comment by AaronV-T** [comment]
AutoBiographer v3.0.5 should fix this issue.
