### ISSUE TITLE
Unsupported GUID lua error in wotlk classic

### ISSUE THREAD

**Issue by Pocokk** [AaronV-T/AutoBiographer#23]
AutoBiographer/HelperFunctions.lua:17: Unsupported GUID: ''.
[string "=[C]"]: in function `error'
[string "@AutoBiographer/HelperFunctions.lua"]:17: in function `GetCatalogIdFromGuid'
[string "@AutoBiographer/Main.lua"]:581: in function `?'
[string "@AutoBiographer/Main.lua"]:124: in function `OnEvent'
[string "@AutoBiographer/Main.lua"]:1351: in function <AutoBiographer/Main.lua:1351>
3
Locals:
Skipped (In Encounter)

I was picked up by the [Constrictor Tentacle npc](https://www.wowhead.com/wotlk/npc=33983/constrictor-tentacle) during the Yogg-Saron encounter, died while I was in its grasp and then I got this lua error (I had a soulstone on me too). Not sure what happened honestly.

**Comment by AaronV-T** [comment]
Thanks for reporting this. I'll add a "Deaths to Unknown" category since it seems some things don't indicate what killed you.

**Comment by Pocokk** [comment]
> Thanks for reporting this. I'll add a "Deaths to Unknown" category since it seems some things don't indicate what killed you.

https://classic.warcraftlogs.com/reports/6AVMtDGhdBLCmXWK#fight=77&type=deaths&death=9

here is the log

**Comment by AaronV-T** [comment]
AutoBiographer v3.0.5 should fix this issue.
