### ISSUE TITLE
Lua error during death in raid

### ISSUE THREAD

**Issue by Pocokk** [AaronV-T/AutoBiographer#24]
I died during a boss fight battle in a raid environment and got this message instantly (using the latest version of the addon)

I later realized its not always tied to death, but rather "combat off", we evaded a boss in raid environment and got the same error.

7x AutoBiographer/Main.lua:450: attempt to compare boolean with number
[string "@AutoBiographer/Main.lua"]:450: in function `?'
[string "@AutoBiographer/Main.lua"]:126: in function `OnEvent'
[string "@AutoBiographer/Main.lua"]:1408: in function <AutoBiographer/Main.lua:1408>

Locals:
Skipped (In Encounter)

**Comment by Pocokk** [comment]
Also got another longer message just now in Alterac Valley bg, not sure what exactly happened

Message: Interface/AddOns/AutoBiographer/Main.lua:450: attempt to compare boolean with number
Time: Fri Apr  7 10:38:31 2023
Count: 1
Stack: Interface/AddOns/AutoBiographer/Main.lua:450: attempt to compare boolean with number
[string "@Interface/AddOns/AutoBiographer/Main.lua"]:450: in function `?'
[string "@Interface/AddOns/AutoBiographer/Main.lua"]:126: in function `OnEvent'
[string "@Interface/AddOns/AutoBiographer/Main.lua"]:1408: in function <Interface/AddOns/AutoBiographer/Main.lua:1408>

Locals: self = <table> {
 PlayerFlags = <table> {
 }
 MailMoneyTakenFromMultipleMessages = <function> defined @Interface/AddOns/AutoBiographer/Main.lua:1064
 LastPlayerMoney = 4016969
 PlayerName = "Erelda"
 TemporaryTimestamps = <table> {
 }
 Frame = Frame {
 }
 RequestTimePlayedInterval = <function> defined @Interface/AddOns/AutoBiographer/Main.lua:1131
 OnStoppedCasting = <function> defined @Interface/AddOns/AutoBiographer/Main.lua:1108
 ClearCharacterData = <function> defined @Interface/AddOns/AutoBiographer/Main.lua:1425
 ClearAllData = <function> defined @Interface/AddOns/AutoBiographer/Main.lua:1411
 UpdateGroupMemberInfo = <function> defined @Interface/AddOns/AutoBiographer/Main.lua:1141
 UpdatePlayerFlags = <function> defined @Interface/AddOns/AutoBiographer/Main.lua:1250
 UpdateMailboxMessages = <function> defined @Interface/AddOns/AutoBiographer/Main.lua:1174
 GetDistanceFromTarget = <function> defined @Interface/AddOns/AutoBiographer/Main.lua:1442
 MailboxClosed = <function> defined @Interface/AddOns/AutoBiographer/Main.lua:1058
 RequestTimePlayed = <function> defined @Interface/AddOns/AutoBiographer/Main.lua:1117
 OnStartedCasting = <function> defined @Interface/AddOns/AutoBiographer/Main.lua:1097
 GameVersion = 3
 MerchantIsOpen = false
 UpdateTimestamps = <function> defined @Interface/AddOns/AutoBiographer/Main.lua:1356
 UpdatePlayerGuildInfo = <function> defined @Interface/AddOns/AutoBiographer/Main.lua:1232
 MailboxUpdatesRunning = 0
 UpdatePlayerZone = <function> defined @Interface/AddOns/AutoBiographer/Main.lua:1336
 OnEvent = <function> defined @Interface/AddOns/AutoBiographer/Main.lua:124
 EventHandlers = <table> {
 }
 MailMoneyTakenFromOneMessage = <function> defined @Interface/AddOns/AutoBiographer/Main.lua:1070
 ZoneChangedNewAreaEventHasFired = true
 PersistentPlayerInfo = <table> {
 }
 PlayerEnteringWorldHasFired = true
 Test = <function> defined @Interface/AddOns/AutoBiographer/Main.lua:1457
 GetPosition = <function> defined @Interface/AddOns/AutoBiographer/Main.lua:1452
 TimePlayedMessageLastTimestamp = 1276.656000
}
timestamp = 1680856710.738000
event = "SPELL_INSTAKILL"
hideCaster = false
sourceGuid = "Player-4749-037D679F"
sourceName = "Pirotia-Earthshaker"
sourceFlags = 1300
sourceRaidFlags = 0
destGuid = "Creature-0-4460-30-31262-26125-00002FD686"
destName = "Risen Ghoul"
destFlags = 8468
destRaidflags = 0
playerCausedThisEvent = false
playerPetCausedThisEvent = false
groupMemberCausedThisEvent = true
damagerUnitId = "raid11"
damagedUnit = <table> {
 FirstObservedDamageCausedByPlayerOrGroup = true
 DamageTakenFromPlayerOrPet = 0
 DamageTakenTotal = 0
 DamageTakenFromGroup = 0
}
damagedUnitId = nil
unitWasOutOfCombat = nil
(*temporary) = false
(*temporary) = false
(*temporary) = "boolean"
(*temporary) = -1
(*temporary) = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = 48743
(*temporary) = "attempt to compare boolean with number"
combatLogDamageEvents = <table> {
 RANGE_INSTAKILL = true
 RANGE_DRAIN = true
 SPELL_BUILDING_DRAIN = true
 SPELL_BUILDING_DAMAGE = true
 SPELL_BUILDING_LEECH = true
 SWING_LEECH = true
 SWING_INSTAKILL = true
 SPELL_PERIODIC_LEECH = true
 SPELL_INSTAKILL = true
 SPELL_PERIODIC_DAMAGE = true
 SWING_DRAIN = true
 SWING_DAMAGE = true
 SPELL_LEECH = true
 SPELL_DAMAGE = true
 SPELL_PERIODIC_INSTAKILL = true
 RANGE_DAMAGE = true
 SPELL_BUILDING_INSTAKILL = true

**Comment by Pocokk** [comment]
Update: I was standing in Dalaran without party/raid (was afk actually) and in no combat, then I got the lua error again

[https://i.imgur.com/YT0wed1.png](https://i.imgur.com/YT0wed1.png)

**Comment by AaronV-T** [comment]
This should be fixed in AutoBiographer v3.0.7, let me know if any issues persist after updating. Thanks!
