### ISSUE TITLE
New lua error occured when I opened the Atlas Loot window and wanted to check an item there

### ISSUE THREAD

**Issue by Pocokk** [AaronV-T/AutoBiographer#25]
7x AutoBiographer/HelperFunctions.lua:63: bad argument #1 to 'gmatch' (string expected, got nil)
[string "=[C]"]: in function `gmatch'
[string "@AutoBiographer/HelperFunctions.lua"]:63: in function `GetItemIdFromTextWithChatItemLink'
[string "@AutoBiographer/Main.lua"]:1128: in function <AutoBiographer/Main.lua:1126>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@MobInfo2/MI2_Events.lua"]:375: in function <MobInfo2/MI2_Events.lua:372>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetSpellByID'
[string "@AtlasLootClassic/Button/Profession_type.lua"]:86: in function `OnEnter'
[string "@AtlasLootClassic/Button/Button.lua"]:125: in function <AtlasLootClassic/Button/Button.lua:118>

Locals:
(*temporary) = nil
(*temporary) = "item:%d+"
(*temporary) = "string expected, got nil"

**Comment by AaronV-T** [comment]
Thanks for reporting this issue, I just released AutoBiographer v.3.1.3 which should fix it.
